### ISSUE TITLE
Unable to Parse JSON file from S3 in AWS Quick Sight

### ISSUE THREAD

**Issue by RubensZimbres** [aws-samples/aws-big-data-blog#100]
I developed a pipeline in AWS where I collect CPU Temperature from my notebook via Python 3 notebook (basicPubSub.py adapted), send to AWS IoT Core using security protocols, updates the shadow successfully, a rule sends data to Cloud Watch and DynamoDB saves it. A Data Pipeline was created to save this DynamoDB data to S3 and I want to generate plots of this data with Quick Sight.

However, I am not being able to make Quick Sight properly read the file. The S3 file looks like this:

`{"timestamp":{"s":"1526819850637"},"payload":{"m":{"$Temperature":{"s":"42.000"}}}}
{"timestamp":{"s":"1526819976032"},"payload":{"m":{"$Temperature":{"s":"42.000"}}}}
{"timestamp":{"s":"1526819934216"},"payload":{"m":{"$Temperature":{"s":"42.000"}}}}
{"timestamp":{"s":"1526817845094"},"payload":{"m":{"$Temperature":{"s":"48.000"}}}}`

When I use the manifest file below, Quick Sight successfully reads data but the 'parseJson' command in New Calculated field disappears, making impossible to read the JSON:

`{
    "fileLocations": [
        {
            "URIs": [
                "https://s3.amazonaws.com/my-bucket2/2018-05-20-12-32-49/12345-a279-1234-2269-491212345"
            ]
        },
        {
            "URIPrefixes": [
                "https://s3.amazonaws.com/my-bucket2/2018-05-20-12-32-49/12345-a279-1234-2269-491212345"
            ]
        }
    ],"globalUploadSettings": {
        "format": "CSV","delimiter":"\n","textqualifier":"'"
    }
}`

Quick Sight reads the JSON as:

`{{"timestamp":{"s":"1526819850637"},"payload":{"m":{"$unknown":{"s":"42.000"}}}}}`

... with no 'parseJson' command.

Data in Quick Sight has no missing values and the AWS pipeline works perfectly until this point. What can I do ?

These are the only formulas available:

avg
ceil
count
dateDiff
decimalToInt
distinct_count
epochDate
extract
floor
intToDecimal
max
min
round
sum
truncDate

... formulas like 'right', 'left', parseJson simply disappear.

**Comment by juksaus** [comment]
You’re reading your JSON to QuickSight as CSV, why’s that?

**Comment by RubensZimbres** [comment]
@juksaus , according to this link (https://docs.aws.amazon.com/quicksight/latest/user/supported-manifest-file-format.html) the supported formats for imported files are CSV, TSV, CLF, and ELF. If there is simpler way to read the JSON file from S3 instead of creating a New Calculated Field, please tell me.

**Comment by RubensZimbres** [comment]
@juksaus I managed to solve the problem:

`{
    "fileLocations": [
        {
            "URIs": [
                "https://s3.amazonaws.com/iot-bucket2/2018-05-20-12-32-49/53034569-a279-4826-b269-4912ef4f0f06"
            ]
        },
        {
            "URIPrefixes": [
                "https://s3.amazonaws.com/iot-bucket2/2018-05-20-12-32-49/53034569-a279-4826-b269-4912ef4f0f06"
            ]
        }
    ],"globalUploadSettings": {"format":"JSON",
        "delimiter":"\n","textqualifier":"'"
    }
}`

Everything is working fine. Thanks a lot for generating such insight.
